name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment"
        required: true
        default: "staging"
        type: choice
        options:
          - staging
          - production
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint

  unit-api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run unit and API tests
        run: npm test

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run production build
        run: npm run build

  e2e-tests:
    runs-on: ubuntu-latest
    needs: [lint, unit-api-tests, build]

    env:
      APP_ENV: ${{ github.event.inputs.environment || 'ci' }}
      TEST_API_KEY: ${{ secrets.TEST_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Verify secret existes
        run: |
          if [ -z "${{ secrets.TEST_API_KEY }}" ]; then
            echo "TEST_API_KEY secret is not set. Please set it in the repository settings."
            exit 1
          fi
          echo "TEST_API_KEY secret is set."

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Show environment variables
        run:  echo "Running pipeline for $APP_ENV environment"

      - name: Run Playwright E2E tests
        run: npm run e2e

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 5

          